image: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.12.2\mingw73_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\
  
build_script:
  - qmake skyscraper.pro
  - mingw32-make

artifacts:
  - path: release\skyscraper.exe
  - path: build\*
